### ISSUE TITLE
Add file icon, v2

### ISSUE THREAD

**Issue by benjamin-thomas** [benjamin-thomas/vscode-roc-lang-extension#3]
The icon provided by @JanCVanB in #1 sets the icon here, in the editor.

![image](https://user-images.githubusercontent.com/1557738/186001175-579ddb28-6257-4b40-a79b-ef5eceb10cae.png)

Plus on the marketplace website.

I'm not seeing the icon here:

![image](https://user-images.githubusercontent.com/1557738/186001512-e79b6d2f-ef5f-4f0f-b675-9bc65dcc6416.png)

Nor in the file tree. So there must be another property to set somewhere.

**Comment by kili-ilo** [comment]
That's actually a separate mechanism that I looked into - file icons vs. extension icons. I couldn't find any way to add a single file type icon without creating an entire file icon theme (a set of rules for all file types), but maybe I missed something.

**Comment by benjamin-thomas** [comment]
Got you, thanks for the info!
